Repository iqbalfarhan/absensimagang, pull requests merged in 2024-03, with the labels that each got.

#2 FEWEB08 - pembimbing - Role and permission
  .gitignore
  README.md
  app/Http/Kernel.php
  app/Livewire/Forms/UserForm.php
  app/Livewire/Pages/Role/Actions.php
  app/Livewire/Pages/Role/Index.php
  app/Models/Attendance.php
  app/Providers/AuthServiceProvider.php
  database/seeders/PermissionSeeder.php
  package.json
  pnpm-lock.yaml
  public/build/assets/app-CifqVuM1.js
  public/build/assets/app-DBCQa6jw.css
  public/build/manifest.json
  resources/css/app.css
  resources/views/components/layouts/app.blade.php
  resources/views/livewire/pages/dokumentasi.blade.php
  resources/views/livewire/pages/role/actions.blade.php
  resources/views/livewire/pages/role/index.blade.php
  resources/views/livewire/partial/footer.blade.php
  resources/views/livewire/partial/navbar.blade.php
  resources/views/livewire/partial/sidebar.blade.php
Labels: draft

#3 FEWEB06 - pembimbing - User management
  README.md
  app/Livewire/Forms/UserForm.php
  app/Livewire/Pages/User/Actions.php
  app/Livewire/Pages/User/Index.php
  app/Livewire/Pages/User/Show.php
  database/factories/UserFactory.php
  resources/css/app.css
  resources/views/components/layouts/app.blade.php
  resources/views/livewire/pages/user/actions.blade.php
  resources/views/livewire/pages/user/index.blade.php
  resources/views/livewire/pages/user/show.blade.php
  resources/views/livewire/partial/footer.blade.php
  resources/views/livewire/partial/navbar.blade.php
  resources/views/livewire/partial/sidebar.blade.php
  routes/web.php
Labels: draft

#4 FEWEB07 - pembimbing - Kode registrasi
  app/Livewire/Pages/Setting/RegistrationCode.php
  app/Models/Setting.php
  database/migrations/2024_03_06_130334_create_settings_table.php
  resources/views/livewire/pages/setting/registration-code.blade.php
Labels: ready to merge

#5 FEWEB09 - halaman registrasi
  app/Livewire/Auth/Register.php
  resources/views/components/layouts/app.blade.php
  resources/views/livewire/auth/login.blade.php
  resources/views/livewire/auth/register.blade.php
Labels: draft

#8 FEWEB04 - pembimbing - Pembuatan halaman dashboard
  app/Livewire/Forms/AttendanceForm.php
  app/Livewire/Pages/Attendance/Actions.php
  app/Livewire/Widget/CheckAttendance.php
  app/Livewire/Widget/Gretting.php
  app/Models/Attendance.php
  database/migrations/2024_03_05_023835_create_attendances_table.php
  resources/views/livewire/pages/attendance/actions.blade.php
  resources/views/livewire/pages/attendance/index.blade.php
  resources/views/livewire/pages/attendance/show.blade.php
  resources/views/livewire/pages/dashboard.blade.php
  resources/views/livewire/widget/check-attendance.blade.php
  resources/views/livewire/widget/gretting.blade.php
Labels: ready to merge

#11 FEWEB04 - pembimbing - Pembuatan halaman dashboard
  app/Livewire/Auth/Login.php
  app/Livewire/Pages/Attendance/Actions.php
  app/Livewire/Pages/Attendance/Index.php
  app/Livewire/Pages/Dashboard.php
  app/Livewire/Pages/User/Actions.php
  app/Livewire/Widget/CountAttendance.php
  app/Livewire/Widget/Profile.php
  app/Models/User.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/UserSeeder.php
  resources/views/livewire/pages/attendance/index.blade.php
  resources/views/livewire/pages/dashboard.blade.php
  resources/views/livewire/pages/role/index.blade.php
  resources/views/livewire/pages/user/index.blade.php
  resources/views/livewire/widget/count-attendance.blade.php
  resources/views/livewire/widget/gretting.blade.php
  resources/views/livewire/widget/profile.blade.php
Labels: draft

#13 FEWEB04 - pembimbing - Pembuatan halaman dashboard
  resources/views/livewire/pages/dashboard.blade.php
Labels: ready to merge

#14 FEWEB11 - Menjaga route sesuai role user yang login
  app/Http/Kernel.php
  app/Livewire/Pages/Role/Index.php
  database/seeders/PermissionSeeder.php
  resources/views/livewire/pages/attendance/index.blade.php
  resources/views/livewire/pages/role/index.blade.php
  resources/views/livewire/pages/user/index.blade.php
  resources/views/livewire/partial/sidebar.blade.php
  resources/views/livewire/widget/check-attendance.blade.php
  routes/web.php
Labels: draft

#15 FEWEB12 - membuat model dan struktur data peta gedung
  app/Livewire/Pages/Office/Actions.php
  app/Livewire/Pages/Office/Index.php
  app/Livewire/Pages/Office/Item.php
  app/Livewire/Pages/Office/Search.php
  app/Models/OfficeMap.php
  database/factories/OfficeMapFactory.php
  database/migrations/2024_03_19_115350_create_office_maps_table.php
  database/seeders/OfficeMapSeeder.php
  database/seeders/PermissionSeeder.php
  resources/views/livewire/pages/office/actions.blade.php
  resources/views/livewire/pages/office/index.blade.php
  resources/views/livewire/pages/office/item.blade.php
  resources/views/livewire/pages/office/search.blade.php
  resources/views/livewire/partial/sidebar.blade.php
  routes/web.php
Labels: ready to merge, draft

#16 NOTICKET - penambahan beberapa fitur dan perbaikan
  database/seeders/DatabaseSeeder.php
  database/seeders/SettingSeeder.php
  resources/views/components/layouts/app.blade.php
  resources/views/livewire/auth/login.blade.php
Labels: ready to merge

#18 FEWEb 13 - siswa - Membuat halaman list peta gedung
  app/Livewire/Pages/Office/Item.php
  resources/views/livewire/pages/office/item.blade.php
  resources/views/livewire/pages/office/search.blade.php
Labels: ready to merge

#19 FEWEB14 - pembimbing - Membuat CRUD action data gedung
  app/Livewire/Forms/OfficeMapForm.php
  app/Livewire/Pages/Office/Actions.php
  app/Livewire/Pages/Office/Index.php
  app/Livewire/Pages/Office/Item.php
  app/Livewire/Pages/Office/Search.php
  app/Livewire/Pages/Office/Show.php
  resources/css/app.css
  resources/views/livewire/pages/dokumentasi.blade.php
  resources/views/livewire/pages/office/actions.blade.php
  resources/views/livewire/pages/office/index.blade.php
  resources/views/livewire/pages/office/item.blade.php
  resources/views/livewire/pages/office/search.blade.php
  resources/views/livewire/pages/office/show.blade.php
Labels: ready to merge
